### PR TITLE
cmdliner: restrict to < 1.0

### PR DESCRIPTION
**Pull request by avsm**
see #496

Signed-off-by: Anil Madhavapeddy <anil@docker.com>

### CODE REVIEW

**Comment by talex5** [comment]
Looks like this change is needed in more places:
```
# File "ci/src/cI_main.ml", line 148, characters 18-22:
# Error: This expression has type
#          ?docv:string ->
#          (string -> ('a, [ `Msg of string ]) Result.result) *
#          'a Cmdliner.Arg.printer -> 'a Cmdliner.Arg.conv
#        but an expression was expected of type
#          'b Cmdliner.Arg.conv =
#            'b Cmdliner.Arg.parser * 'b Cmdliner.Arg.printer
```

**Comment by avsm** [comment]
Pushed more constraints and rebased.

**Comment by avsm** [comment]
Looks like the master branch tests run different tests than on PRs -- this looks like an unrelated bug.

```
#=== ERROR while installing datakit-bridge-local-git.dev ======================#
# opam-version         1.2.2
# os                   linux
# command              ocaml pkg/pkg.ml build --pinned true -n datakit-bridge-local-git
# path                 /home/opam/.opam/system/build/datakit-bridge-local-git.dev
# compiler             system (4.04.0)
# exit-code            1
# env-file             /home/opam/.opam/system/build/datakit-bridge-local-git.dev/datakit-bridge-local-git-7-1872ec.env
# stdout-file          /home/opam/.opam/system/build/datakit-bridge-local-git.dev/datakit-bridge-local-git-7-1872ec.out
# stderr-file          /home/opam/.opam/system/build/datakit-bridge-local-git.dev/datakit-bridge-local-git-7-1872ec.err
### stdout ###
# ocamlfind ocamlopt unix.cmxa -I /home/opam/.opam/system/lib/ocamlbuild /home/opam/.opam/system/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /home/opam/.opam/system/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# ocamlfind ocamldep -package 'irmin.unix, irmin.git, irmin-watcher, datakit-github' -package 'cmdliner, logs, datakit-client, protocol-9p.unix, fmt.cli, fmt.tty, logs.cli' -package 'bytes lwt astring logs result cstruct fmt rresult' -package datakit-github,datakit-client -modules bridge/local/main.ml > bridge/local/main.ml.depends
# + ocamlfind ocamldep -package 'irmin.unix, irmin.git, irmin-watcher, datakit-github' -package 'cmdliner, logs, datakit-client, protocol-9p.unix, fmt.cli, fmt.tty, logs.cli' -package 'bytes lwt astring logs result cstruct fmt rresult' -package datakit-github,datakit-client -modules bridge/local/main.ml > bridge/local/main.ml.depends
# ocamlfind: Package `irmin.unix' not found
# Command exited with code 2.
### stderr ###
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tag' 'debug'
#      '-build-dir' '_build' '-Is' 'bridge/local' '-package'
#      'datakit-github,datakit-client' 'CHANGES.md' 'LICENSE.md' 'README.md'
#      'bridge/local/main.native']: exited with 10
```

**Comment by talex5** [comment]
This doesn't look good:
```
The following dependencies couldn't be met:
  - datakit -> cmdliner < 1.0.0
    unavailable for unknown reasons (this may be a bug in opam)
```

**Comment by avsm** [comment]
This is using opam2?

**Comment by talex5** [comment]
Yes.

**Comment by avsm** [comment]
The irmin.unix failure should be fixed in https://github.com/avsm/mirage-ci/commit/62d3f1be9ca9de2063ffc3649422a5c36a4ec1ac -- we may have a split universe with cmdliner deps at the moment though.

**Comment by talex5** [comment]
Yes, we can't upgrade datakit to cmdliner 1.0.0 because then we'd need git 1.10.0 too, and that conflicts with irmin 0.12.0. I think @samoht may be working on irmin 1.0.0 support in DataKit.

**Comment by samoht** [comment]
See: 
- https://github.com/mirage/ocaml-git/pull/202
- https://github.com/mirage/irmin/pull/423

I am not working on irmin 1.0 support in DataKit this week.

**Comment by avsm** [comment]
we can't have datakit docs on docs.mirage.io until cmdliner 1.0 support, since odig depends on that and it generates the docs :)

**Pull request merged**
