### PR TITLE
reorganize internal libraries to avoid library leakage and linking with wrong archive

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
@dbuenzli: `metagen` gives some false positive but it's already pretty useful. e.g.

```
$ metagen datakit-client
 archive(native) = "datakit-client.cmxa"
 plugin(byte) = "datakit-client.cma"
 plugin(native) = "datakit-client.cmxs"
-requires = "astring cstruct fmt logs lwt protocol-9p result"
+requires = "astring cstruct fmt io-page.io_page ipaddr logs lwt protocol-9p result sexplib"

$ metagen datakit-server
 archive(native) = "fs9p.cmxa"
 plugin(byte) = "fs9p.cma"
 plugin(native) = "fs9p.cmxs"
-requires = "astring cstruct datakit-server.vfs fmt logs protocol-9p result rresult sexplib"
+requires = "astring cstruct datakit-server.vfs fmt io-page.io_page ipaddr logs lwt protocol-9p result rresult sexplib"

$ metagen datakit-github
 archive(native) = "datakit-github.cmxa"
 plugin(byte) = "datakit-github.cma"
 plugin(native) = "datakit-github.cmxs"
-requires = "datakit-client datakit-server.vfs github"
+requires = "astring biniou cohttp cohttp.lwt conduit conduit.lwt-unix cstruct datakit-client datakit-server.vfs fieldslib fmt github-hooks github-hooks.github_hooks github-hooks.github_hooks_unix github-hooks.unix github.core github.unix ipaddr logs lwt lwt.unix result rresult sexplib uri"
```

There are clearly some missing deps in `datakit-github` I will fix that later on. For the other packages, it gives too many dependencies.

**Comment by dbuenzli** [comment]
> @dbuenzli: metagen gives some false positive

What do you mean by false positive ?

**Comment by samoht** [comment]
`io-page.io_page` is a bit weird (and doesn't exists). `ipaddr` and `sexplib` are not direct dependencies of `datakit-github`.

**Comment by samoht** [comment]
Last TravisCI error should hopefully be fixed by https://github.com/ocaml/opam-repository/pull/7579

**Comment by samoht** [comment]
All green, merging!

**Pull request merged**
