### PR TITLE
github-bridge: avoid triggering GitHub hyperlinks in merge messages

### PR DESCRIPTION
**Pull request by samoht**
Signed-off-by: Thomas Gazagnaire <thomas@gazagnaire.org>

### CODE REVIEW

**Comment by avsm** [comment]
ha! its actually quite nice to see the CI commits to know its happened...

**Comment by samoht** [comment]
I find it a bit spammy (and apparently @talex5 too). But I have no strong opinion either way.

**Comment by samoht** [comment]
@talex5: any opinion?

**Comment by talex5** [comment]
Yeah, seems spammy to me too. You can tell that the bridge is working anyway because a DataKitCI status will appear on your PR.

**Pull request merged**
