### PR TITLE
github: rewrite the scheduler loop to ensure that rate-limiting is re…

### PR DESCRIPTION
**Pull request by samoht**
…spected

All operations should be done in same GitHub monad to ensure that rate-limiting
headers are actually read and obeyed by the libary.

Signed-off-by: Thomas Gazagnaire <thomas@gazagnaire.org>

### CODE REVIEW

**Comment by dsheets** [comment]
This is the first application to use the rate-limiting functionality in anger. Please report any issues. Thanks!

**Comment by samoht** [comment]
@talex5 the logs say:

```
# File "ci/src/cI_web_templates.mli", line 32, characters 34-56:
# Error: Unbound module Tyxml
```

Any idea what could have caused this?

**Comment by talex5** [comment]
Missing version contraint on Tyxml (should be `>= "4.0.0"` I think).

**Pull request merged**
