### PR TITLE
retry named pipe connection on failure

### PR DESCRIPTION
**Pull request by simonferquel**
Tentative to fix Named pipe accept problems with Pinata

### CODE REVIEW

**Comment by talex5** [comment]
@djs55 I don't understand how this is supposed to work. What does the bool returned by `connect` mean, and how should it be handled? The docs just say:

```
val connect: t -> bool Lwt.t
(** Connect blocks until a client connects to this named pipe *)
```

(also, there's a `let _ = ` a few lines below, which will probably make debugging problems harder than it needs to be by suppressing any exceptions that get thrown...)

**Comment by simonferquel** [comment]
From the existing code, I would say that the Boolean indicates success or failure of connect, but I might be wrong.
My PR just reattempt the connection (in case the named pipe has not yet been freed by a previous instance). (for now I just made the PR, so I can get a build - for whatever reason I can't build datakit locally)

**Comment by djs55** [comment]
I believed `true` means connected and `false` means something went wrong (I'm not sure why I didn't throw `Unix_error` in that case). I probably copied the style of the C function:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365146(v=vs.85).aspx

**Comment by samoht** [comment]
I am working on an improved version of the named-pipe binding: https://github.com/mirage/ocaml-named-pipe/pull/14 which fixes the API too (and add some debugging statements).

I'll update the code in that PR to use this when this is ready (should be soon).

**Comment by simonferquel** [comment]
This project fixes the issue on pinata. However something since last release seem to make it much more verbose in term of logging (every read is logged)

**Comment by samoht** [comment]
Closing as #333 is not in.

**Pull request closed without merging**
