### PR TITLE
README wording tweaks

### PR DESCRIPTION
**Pull request by yallop**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks, but can you sign-off your commit? https://github.com/docker/datakit/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by talex5** [comment]
LGTM (once sign-off is added).

**Comment by samoht** [comment]
@thaJeztah is it easy to set up the bot to check for this?

**Comment by thaJeztah** [comment]
@samoht it's done through both https://github.com/docker/leeroy, and https://github.com/docker/docker/blob/master/hack/make/validate-dco

perhaps @icecrime knows how the bot (Leeroy) is set up

**Comment by thaJeztah** [comment]
But I'd love to have a document describing how to set it all up :smile:

**Comment by ijc25** [comment]
@icecrime, @thaJeztah: I'd love to have DCO checking for docker/hyperkit too...

**Comment by yallop** [comment]
I've signed the commit (e60f570).

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
